### ISSUE TITLE
[Issue] EJS does not work properly after "default syntax only" check in

### ISSUE THREAD

**Issue by saintc0d3r** [samholmes/EJS.tmLanguage#10]
Hello samholmes,

I have just noticed that EJS.tmLanguage plugin shows error when I open an .ejs file in my Sublime 3 a while ago. Then, I uninstalled the EJS.tmLanguage through Package control and re-installed it again, but the error still occurs. It seems that this error is caused by your latest check in "default syntax only". Here are the steps to replicate the issue:
1. Reinstall/Upgrade EJS.tmLanguage by using Package Control in Sublime 3.
2. Close & Reopen Sublime 3 text editor app.
3. Confirm that an Error occurs "Error parsing snippet xml: expected=in file Packages/EJS/insert_ejs_tags.sublime-snippet on line:5".
4. Click [Ok] button on the error dialog.
5. Open an .ejs file.
6. Confiirm that the syntax highlighting on the .ejs file is gone now. 

Below is the detail of my system environment:
- Ubuntu 14.04
- Sublime 3 with these installed Packages (in Package Control): Angular JS, Better Completion, Better Coffeescript.

Cheers.

**Comment by keeganbrown** [comment]
+1

**Comment by samholmes** [comment]
I believe 7d56ebd2dcdbf73eae5a936f96a32ba26f1aab20 fixed this issue, but I prefer @dgmike's solution which is reflected in 298ad325c28878ed1ca440b2878756e67b94f389. Closing as I believe this issue has been resolved.
