### ISSUE TITLE
Error parsing snippet xml: expected = in file Packages/EJS/insert_ejs_tags.sublime-snippet on line: 5

### ISSUE THREAD

**Issue by mikeelston** [samholmes/EJS.tmLanguage#11]
After installing the latest Sublime Text 3 Package (2014.05.30.20.12.54)
Each time i open Sublime Text 3 i get a prompt 

```
Error parsing snippet xml: expected = in file Packages/EJS/
insert_ejs_tags.sublime-snippet on line: 5
```

![Screenshot - Imgur](http://i.imgur.com/TehZN7p.png)

**Comment by samholmes** [comment]
Fixed with 298ad325c28878ed1ca440b2878756e67b94f389
