### ISSUE TITLE
When I use <% %> brackets it disables html completions. 

### ISSUE THREAD

**Issue by vhflat** [samholmes/EJS.tmLanguage#17]
As you can see in the picture it seems that the `<% %>` -brackets are disturbed by the `<p></p>`

![screen shot 2016-10-13 at 21 34 47](https://cloud.githubusercontent.com/assets/11570271/19364103/204cce04-918d-11e6-8a74-abed583d5216.png)

Do you know how to fix this? Cos I really love the html completions 👍

**Comment by samholmes** [comment]
Looks like the issue is that the if condition is causing scope to remain in `scope.js`. Not sure why.

**Comment by samholmes** [comment]
Duplicate of #16 and #14
