### ISSUE TITLE
EJS is no longer available to install via ST3's Package Control

### ISSUE THREAD

**Issue by medallyon** [samholmes/EJS.tmLanguage#18]
I can't seem to be able to find this package in Sublime Text 3's Package Control anymore.

The page at [Package Control](https://packagecontrol.io/packages/EJS) returns the following warning: `Package info was unavailable last time crawler ran. Unable to download https://api.github.com/repos/samholmes/EJS.tmLanguage after 3 attempts`.

**Comment by samholmes** [comment]
Seems like an issue on Package Control's part. Could you file an issue over on Package Control: https://github.com/wbond/package_control/issues

**Comment by medallyon** [comment]
Looks like it's fine again? Maybe they had some kinda outage for some packages (I remember trying to install EJS 2, their page had the same issue).
