### ISSUE TITLE
detection of <% vs <? is off

### ISSUE THREAD

**Issue by saelfaer** [samholmes/EJS.tmLanguage#7]
when opening files with `<%%>` notation It detects the syntax highlighting as EJS `<??>`...

i can switch it over manually but that gets tedious after doing that for every template time and time again. 

either I'm looking for an option to force `<%%>` syntax highlighting, or a fix to detect the syntax type.

**Comment by samholmes** [comment]
Like I said in 2014, I'm open to a PR on this one. As of right now the plugin supports you choosing between the two EJS styles of code. It would be cool if my plugin could detect between the two styles, but I'm not too familiar as to how this would be done (so a PR would be greatly appreciated).
